# Generated by Django 5.2.8 on 2025-12-19 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractorLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_document', models.FileField(upload_to='contractor_licenses/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contractor', models.OneToOneField(limit_choices_to={'role': 'contractor'}, on_delete=django.db.models.deletion.CASCADE, related_name='contractor_license', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
