# Generated by Django 5.2.8 on 2026-04-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='client_profiles/'),
        ),
    ]
