# Generated by Django 5.2.8 on 2025-12-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0002_contractorlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorlicense',
            name='attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='contractorlicense',
            name='extracted_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contractorlicense',
            name='match_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contractorlicense',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contractorlicense',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='contractorlicense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
