# Generated by Django 5.2.8 on 2026-02-11 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentication', '0003_contractorlicense_attempts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('contractor', 'Contractor'), ('worker', 'Worker'), ('admin', 'Admin')], default='client', max_length=20),
        ),
    ]
