# Generated by Django 5.2.8 on 2026-02-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IssueSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='reports/attachments/'),
        ),
        migrations.AddField(
            model_name='report',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=20),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(default='No Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('PAYMENT', 'Payment'), ('BID', 'Bid'), ('PROJECT', 'Project'), ('CHAT', 'Chat Message'), ('ACCOUNT', 'Account'), ('BUG', 'Bug'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('REJECTED', 'Rejected')], default='OPEN', max_length=20),
        ),
    ]
