# Generated by Django 5.2.8 on 2026-02-25 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0002_projectassignment'),
        ('RecommendationSystem', '0006_project_daily_rate_project_hiring_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_job_applications', to='RecommendationSystem.project')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_job_applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
