# Generated by Django 5.2.8 on 2026-02-26 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0004_alter_task_assigned_to_alter_task_contractor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectprogressupdate',
            name='milestone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='progress_updates', to='ProgressTracking.milestone'),
        ),
    ]
