# Generated by Django 5.2.8 on 2026-02-28 09:22

from django.db import migrations, models
from collections import defaultdict

def remove_duplicates(apps, schema_editor):
    """Remove duplicate work logs, keeping the earliest one for each worker/project/date."""
    WorkLog = apps.get_model('ProgressTracking', 'WorkLog')
    
    # Group all logs by (worker, project, date)
    dupes = defaultdict(list)
    for log in WorkLog.objects.all().order_by('created_at'):
        key = (log.worker_id, log.project_id, log.date)
        dupes[key].append(log.id)
    
    # For each group with >1 entry, delete all but the first (oldest)
    to_delete = []
    for key, log_ids in dupes.items():
        if len(log_ids) > 1:
            to_delete.extend(log_ids[1:])  # keep first, delete rest
    
    if to_delete:
        WorkLog.objects.filter(id__in=to_delete).delete()
        print(f"Deleted {len(to_delete)} duplicate work logs.")

class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0005_projectprogressupdate_milestone'),
    ]

    operations = [
        migrations.RunPython(remove_duplicates, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('REJECTED', 'Rejected'), ('REWORK', 'Rework Required'), ('COMPLETED', 'Completed'), ('APPROVED', 'Approved')], default='PENDING', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='worklog',
            unique_together={('worker', 'project', 'date')},
        ),
    ]
