# Generated by Django 5.2.8 on 2026-03-11 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0007_remove_duplicate_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=15),
        ),
    ]
