# Generated by Django 5.2.8 on 2026-03-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0008_worklog_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worklog',
            name='description',
        ),
        migrations.AddField(
            model_name='worklog',
            name='transaction_uuid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
