# Generated by Django 5.2.8 on 2026-03-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProgressTracking', '0009_remove_worklog_description_worklog_transaction_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='worklog',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
