# Generated by Django 5.2.8 on 2025-12-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='availability_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Busy', 'Busy'), ('Unavailable', 'Unavailable')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='contractor_type',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Company', 'Company')], default='Individual', max_length=20),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='rate_type',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Project', 'Project')], default='Project', max_length=20),
        ),
    ]
