# Generated by Django 5.2.8 on 2026-04-03 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='contractor_profiles/'),
        ),
    ]
