# Generated by Django 5.2.8 on 2026-04-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0002_contractor_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
    ]
