# Generated by Django 5.2.8 on 2026-03-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0005_workerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='experience_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='worker_profiles/'),
        ),
        migrations.AddField(
            model_name='workerprofile',
            name='specialization',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
