# Generated by Django 5.2.8 on 2026-03-11 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0006_workerprofile_bio_workerprofile_experience_years_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerprofile',
            name='profile_picture',
        ),
    ]
