# Generated by Django 5.2.8 on 2026-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContractorManagement', '0007_remove_workerprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
