# Generated by Django 6.0.3 on 2026-04-03 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ProgressTracking', '0001_initial'),
        ('RecommendationSystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('transaction_uuid', models.CharField(max_length=50, unique=True)),
                ('transaction_code', models.CharField(blank=True, default='', max_length=30)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='INITIATED', max_length=12)),
                ('payment_type', models.CharField(choices=[('ADVANCE', 'Advance'), ('MILESTONE', 'Milestone'), ('FINAL', 'Final')], default='FINAL', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payments', to=settings.AUTH_USER_MODEL)),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='ProgressTracking.milestone')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='RecommendationSystem.project')),
            ],
        ),
    ]
