# Generated by Django 5.2.8 on 2025-12-27 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CIVIL', 'Civil'), ('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('INTERIOR', 'Interior'), ('PAINTING', 'Painting'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BIDDING', 'Bidding'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='BIDDING', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
