# Generated by Django 6.0.3 on 2026-04-03 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('CIVIL', 'Civil'), ('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('INTERIOR', 'Interior'), ('PAINTING', 'Painting'), ('OTHER', 'Other')], max_length=20)),
                ('location', models.CharField(max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True)),
                ('description', models.TextField()),
                ('budget', models.PositiveIntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('BIDDING', 'Bidding'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='BIDDING', max_length=15)),
                ('hiring_model', models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_PROJECT', 'Per Project')], default='PER_PROJECT', max_length=20)),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate if hiring model is Per Day', max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('ESEWA', 'eSewa')], max_length=10, null=True)),
                ('advance_paid', models.BooleanField(default=False)),
                ('work_completed', models.BooleanField(default=False)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('final_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('assigned_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_projects', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
