# Generated by Django 5.2.8 on 2026-02-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0002_project_assigned_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_amount',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('ESEWA', 'eSewa')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Paid')], default='UNPAID', max_length=10),
        ),
    ]
