# Generated by Django 5.2.8 on 2026-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0005_alter_project_latitude_alter_project_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Daily rate if hiring model is Per Day', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='hiring_model',
            field=models.CharField(choices=[('PER_DAY', 'Per Day'), ('PER_PROJECT', 'Per Project')], default='PER_PROJECT', max_length=20),
        ),
    ]
