# Generated by Django 5.2.8 on 2026-03-13 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecommendationSystem', '0006_project_daily_rate_project_hiring_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='work_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='payment_status',
            field=models.CharField(choices=[('UNPAID', 'Unpaid'), ('PARTIALLY_PAID', 'Partially Paid'), ('PAID', 'Paid')], default='UNPAID', max_length=20),
        ),
    ]
