# Generated by Django 5.2.8 on 2026-02-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiddingSystem', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='daily_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
